Use autossh instead of ssh
kingsquare/docker-tunnel pull request #4
Opened 2017-01-10 09:09 UTC by bubak4

For extra reliability I can recommend using autossh instead of ssh (minor change in Dockerfile).

I have also added a simple (GNU) Makefile for container build and updated doc accordingly.

2017-01-11 10:24 UTC, fruitl00p requested changes
I've looked over your proposal... Please review these and see if we can merge at least the core: autossh + updated alpine...

2017-01-11 10:24 UTC, fruitl00p commented on Dockerfile
> +FROM alpine:latest
I can agree on using a later alpine version, but `:latest` is not recommended. Could you change this to 3.5? That at least reflects the actual used version ;)

2017-01-11 10:24 UTC, fruitl00p commented on Dockerfile
> +MAINTAINER bubak4 <mar@centrum.cz>
We might want to remove the maintainers as a whole .. see docker/docker#25466
Possibly include a label referring to this repo ... that has more info anyway on the subject (code authors etc)

2017-01-11 10:24 UTC, fruitl00p commented on Dockerfile
> +ENTRYPOINT ["/usr/bin/autossh", "-M", "0", "-T", "-N", "-oStrictHostKeyChecking=no", "-L"]
if replacing ssh with autossh, you still want to keep the `ServerAliveInterval=180` setting... (as you've disabled the monitoring rightly so)

2017-01-11 10:24 UTC, fruitl00p commented on Makefile
> +TAG=bubak4
i understand you're tag, but this shouldnt be in the original repo IMHO

2017-01-11 10:24 UTC, fruitl00p commented on README.md
> +
i understand the recommendation, but i dont see how thats better? Its up to the local ssh-agent in the original case to have the correct identities... (and using the -i option would require volume-ing that in as well... )

2017-01-13 09:36 UTC, bubak4 commented on Dockerfile
> +FROM alpine:latest
no problem, will change to 3.5

2017-01-13 09:37 UTC, bubak4 commented on Dockerfile
> +MAINTAINER bubak4 <mar@centrum.cz>
no problem, I just copied the line with my name as I thought you do it that way, I do not use it either, will remove

2017-01-13 09:41 UTC, bubak4 commented on Dockerfile
> +ENTRYPOINT ["/usr/bin/autossh", "-M", "0", "-T", "-N", "-oStrictHostKeyChecking=no", "-L"]
I use autossh reliably without the ServerAliveInterval, but I did some search on the Internet and it is recommended to be used, so be it :-)

2017-01-13 09:50 UTC, bubak4 commented on README.md
> +
In my deployments I am just used to import project specific keys -- I like to be explicit what keys are used (and make them part of the container) than to rely on local agent to provide the identities.   But I have no intention to change that in your repository, as I have not yet found good enough solution to generate and provide those keys -- it always requires a bit of shell scripting

2017-01-13 11:58 UTC, bubak4 commented on Makefile
> +TAG=bubak4
well, in fact I did not expect you will integrate my Makefile at all, so I was not extra careful -- it is a bit Linux specific as this is my platform of choice -- I just included the Makefile just for my own reference as I use Makefile a lot to automate docker container builds.  I will make a bit nicer, though it always involves a bit of work to modify it specific needs.

Feel free to ignore the Makefile.

2017-01-28 12:54 UTC, bubak4 commented
Sorry it took longer than I expected, I was quite busy those days.  Closing this request & creating another one with your suggestions incorporated.

2017-01-28 12:54 UTC, closed without merging